### ISSUE TITLE
二つ以上ルートブロックがある時の動作

### ISSUE THREAD

**Issue by rayofhopejp** [eeicmayfes2021/mayfes2021-pkyo#33]
blockly、二つ以上ルートブロック（ブロックのかたまり）がある時にどっちが先に読み込まれるか未知数なので
二つ以上のルートブロックを許さないようにするか、どっちが先に読み込まれるかを指定するかしないとややこしい気がする

**Comment by nawawan** [comment]
結局これも大丈夫なので良し！
