### ISSUE TITLE
ゲーム画面の改良

### ISSUE THREAD

**Issue by nawawan** [eeicmayfes2021/mayfes2021-pkyo#39]
ボタンの位置とか、リセットボタンの位置とかを変更するべきでしょっという気持ち

Blockが表示される部分にボタンがあるの、なかなかやばいと思っています
ゲーム画面の下側に新しくなにか置くスペースをつくるべきかと

**Comment by rayofhopejp** [comment]
これにプラスして「看板を目指そう！」などの軽い説明が表示される場所が必要そうです

**Comment by nawawan** [comment]
説明(というか注意)を付け加えたのでヨシ！
