### ISSUE TITLE
ゴール判定の実装

### ISSUE THREAD

**Issue by nawawan** [eeicmayfes2021/mayfes2021-pkyo#4]
ゴールした際に「次のステージへ」とかがでるようにしたいです。

いきなりこれは実装できないと思うので、ゴールしたらコンソールになんか出る程度でOKですのでおねがいします。

余裕がある人はゴールしたら何かを画面に表示する的な何かをお願いします。

**Comment by rayofhopejp** [comment]
#13 で一応実装しました

**Comment by nawawan** [comment]
動画見た限りちゃんと判定できていそうだったのでcloseします
