### ISSUE TITLE
タイトル画面の実装

### ISSUE THREAD

**Issue by nawawan** [eeicmayfes2021/mayfes2021-pkyo#5]
これはまぁシーン遷移とかの話になるんですが、想定としてはタイトルでボタンを押したらゲームが始まる的な感じです。

ボタン押したら〜部分はJS書いてPhaserのsceneの部分をいじればなんとかなりそうな気がします(調べるなりリファレンスを読むなりする必要があると思います)。

**Comment by rayofhopejp** [comment]
7b3966d68ca3e1dbb1c2bd28f1408f9f55d7995f

**Comment by nawawan** [comment]
これもできていそうなのでcloseします
